# Autogenerated by nbdev

d = { 'settings': { 'branch': '1',
                'doc_baseurl': '/auto_economics',
                'doc_host': 'https://uh2000.github.io',
                'git_url': 'https://github.com/uh2000/auto_economics',
                'lib_path': 'auto_economics'},
  'syms': {'auto_economics.core': {}}}
