# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['a', 'b', 'c', 'd', 'supply_function', 'demand_function', 'market', 'supply', 'demand']

# %% ../nbs/00_core.ipynb 3
import matplotlib.pyplot as plt
from sympy import symbols, Eq, solve, diff, integrate
import sympy
import numpy as np
import random
import math

# %% ../nbs/00_core.ipynb 4
from free_market import Free_market

a = random.randint(1,5)
b = random.randint(5,10)
c = random.randint(1,5)
d = random.randint(0,1)
supply_function = f"{d} + {c}*x"
demand_function = f"{b} - {a}*x"
market = Free_market(supply_function, demand_function)

print(f"supply function {supply_function}\ndemand function {demand_function}")

# %% ../nbs/00_core.ipynb 5
from monopoly import Monopoly

supply = "2*x**2"
demand = "50*x -  3*x**2"
market = Monopoly(supply, demand)
market.get_graph(complete=True, is_tot_cost = True)
