# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_core.ipynb 3
import matplotlib.pyplot as plt
from sympy import symbols, Eq, solve, diff, integrate, parse_expr
import sympy
import numpy as np
import random
import math

# %% ../nbs/00_core.ipynb 4
from free_market import Free_market


# %% ../nbs/00_core.ipynb 6
from monopoly import Monopoly
    

